# project information
site_name: "Omio CNC X6-2200EPL Documentation"
site_author: "Stephen Eaton"
site_description: "Documentation for OmioCNC X6-2200EPL CNC Router"
site_url: https://madeinoz67.github.io/omiocnc-x6-2200epl/

# Configuration
theme:
  name: material
  favicon: assets/images/favicon.ico
  palette:
    primary: orange
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top

# Page Tree
nav:
  - Home: index.md
  - Hardware:
      - hardware/index.md
      - Controller: hardware/controller.md
      - Spindle: hardware/spindle.md
  - Firmware:
      - firmware/index.md
  - Modifications & Improvements:
      - mods/index.md
      - Spindle Cooling: mods/cooling.md
      - Simple Chip Shield: mods/shield.md
      - Air Mister: mods/air.md
      - Table: mods/table.md
      - Fixture Plate: mods/fixture-plate.md
  - CAM post processors:
      - cam/index.md
  - PCB Milling:
      - pcb/index.md
  - G-Code Library:
      - gcode/index.md
      # - Commands: gcode/gcode-commands.md
      # - Macros: gcode/gcode-macros.md
      # - Setting: gcode/gcode-settings.md
      # - Troubleshooting: gcode/gcode-troubleshooting.md
  - Checklists:
      - checklists/index.md
      - sample: checklists/sample.md
  - Troubleshooting:
      - troubleshooting/index.md
  - Authors: authors.md
  - Change Log: changelog.md
  - License: license.md
  - References: references.md

# Repository
repo_name: "madeinoz67/omiocnc-x6-2200epl"
repo_url: https://github.com/madeinoz67/omiocnc-x6-2200epl
edit_uri: ""

# plugins
plugins:
  - search
  - ezlinks
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - drawio-exporter
  - thumbnails:
      # optional styling for the thumbnail:
      style: margin-top:5px;margin-bottom:5px;margin-right:25px

# extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.keys
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - markdown.extensions.attr_list

# Copyright
copyright: Copyright &copy; 2021 Stephen Eaton

# footer customisation
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/madeinoz67
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/madeinoz
# Google Analytics
#google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
# - auto
