name: Publish docs via GitHub Pages on release
on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
env:
  PYTHON_VERSION: 3.9.x
  POETRY_VERSION: 1.1.11

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install snapd
        run:  apt install snapd

      - name: install drawio
        run:  snap install drawio

      - name: Set up Python runtime
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: View poetry version
        run: poetry --version

      - name: Install project dependencies
        run: poetry install

      - name: Deploy documentation
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          poetry run mkdocs gh-deploy --force
          poetry run mkdocs --version
